"""Validate the public records and generate file-preview-friendly winners.js."""
import json
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAYMENT = {"unknown", "winner_reports_unpaid", "winner_reports_paid", "payment_evidence_reviewed"}

def check_date(value, allow_null=False):
    if value is None and allow_null:
        return
    assert isinstance(value, str) and re.fullmatch(r"\d{4}-\d{2}-\d{2}", value), "Dates must be YYYY-MM-DD"
    date.fromisoformat(value)

def build():
    data = json.loads((ROOT / "data/winners.json").read_text(encoding="utf-8"))
    assert data["schemaVersion"] == 1, "Unsupported schema version"
    check_date(data["updatedAt"])
    assert isinstance(data["records"], list), "records must be an array"
    ids = set()
    for r in data["records"]:
        assert re.fullmatch(r"COB-\d{3,}", r["id"]) and r["id"] not in ids, "Invalid or duplicate ID"
        ids.add(r["id"])
        assert isinstance(r["winner"], str) and re.fullmatch(r"[A-Za-z0-9_]{1,25}", r["winner"]), "Use a public Twitch username"
        check_date(r["winDate"], allow_null=True)
        check_date(r["paymentCheckedAt"], allow_null=True)
        assert r["paymentStatus"] in PAYMENT, "Invalid payment status"
        assert r["announcementStatus"] in {"needs_review", "reviewed"}, "Invalid announcement status"
        assert r["sourceType"] in {"claimant_report", "manual_vod_review", "reviewed_chat_detection"}, "Invalid source type"
        amount = r["prize"]["amount"]
        assert isinstance(amount, (float, int)) and not isinstance(amount, bool) and 0 <= amount < 1e9, "Invalid prize amount"
        assert r["prize"]["currency"] in {"USD"}, "Add supported currencies deliberately"
        assert isinstance(r["prize"]["kind"], str) and r["prize"]["kind"], "Prize kind is required"
        assert r["vodId"] is None or re.fullmatch(r"\d+", r["vodId"]), "Invalid VOD ID"
        seconds = r["timestampSeconds"]
        assert seconds is None or (type(seconds) is int and 0 <= seconds < 604800), "Invalid VOD timestamp"
        assert (r["vodId"] is None) == (seconds is None), "VOD and timestamp must be supplied together"
        for evidence in r["evidenceLinks"]:
            url = evidence["url"]
            assert isinstance(evidence["label"], str) and evidence["label"], "Evidence label required"
            assert url.startswith("https://") or re.fullmatch(r"evidence/[A-Za-z0-9_.-]+", url), "Use HTTPS or an evidence file"
        assert isinstance(r["notes"], str), "notes must be text"
        for entry in r["history"]:
            check_date(entry["date"])
            assert isinstance(entry["event"], str), "History event must be text"
    # JSON is serialized as data; never evaluate chat text as executable code.
    serialized = json.dumps(data, ensure_ascii=True, indent=2, allow_nan=False).replace("<", "\\u003c").replace(">", "\\u003e")
    (ROOT / "data/winners.js").write_text("// Generated by scripts/build_data.py. Edit winners.json instead.\nwindow.PRIZE_DATA = " + serialized + ";\n", encoding="utf-8")
    print(f"Validated and generated {len(data['records'])} record(s).")

if __name__ == "__main__":
    build()
